//! Tool definitions, calls, and results.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Tool Definition (schema for LLM function-calling)
// ---------------------------------------------------------------------------

/// A tool that agents can invoke.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// Unique tool name (e.g. "web_search", "mcp_github_list_repos").
    pub name: String,
    /// Human-readable description shown to the LLM.
    pub description: String,
    /// JSON Schema for the tool's parameters.
    pub parameters: serde_json::Value,
    /// Source of the tool: "builtin", "mcp:{server_name}", "plugin".
    #[serde(default = "default_source")]
    pub source: String,
}

fn default_source() -> String {
    "builtin".into()
}

// ---------------------------------------------------------------------------
// Tool Call (LLM requests tool execution)
// ---------------------------------------------------------------------------

/// A tool invocation requested by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Unique call ID (generated by the LLM or synthetic).
    pub id: String,
    /// Tool name to invoke.
    pub name: String,
    /// JSON-encoded arguments string.
    pub arguments: String,
}

impl ToolCall {
    /// Parse arguments as a JSON value.
    pub fn parsed_arguments(&self) -> Result<serde_json::Value, serde_json::Error> {
        serde_json::from_str(&self.arguments)
    }

    /// Parse arguments into a typed map.
    pub fn arguments_map(&self) -> Result<HashMap<String, serde_json::Value>, serde_json::Error> {
        serde_json::from_str(&self.arguments)
    }
}

// ---------------------------------------------------------------------------
// Tool Result (tool execution output)
// ---------------------------------------------------------------------------

/// Result of executing a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    /// The call ID this result corresponds to.
    pub call_id: String,
    /// Whether the tool execution succeeded.
    pub success: bool,
    /// Output content (text result or error message).
    pub output: String,
}

impl ToolResult {
    /// Create a successful tool result.
    pub fn ok(call_id: impl Into<String>, output: impl Into<String>) -> Self {
        Self {
            call_id: call_id.into(),
            success: true,
            output: output.into(),
        }
    }

    /// Create a failed tool result.
    pub fn err(call_id: impl Into<String>, error: impl Into<String>) -> Self {
        Self {
            call_id: call_id.into(),
            success: false,
            output: error.into(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tool_call_parse_arguments() {
        let tc = ToolCall {
            id: "call_1".into(),
            name: "web_search".into(),
            arguments: r#"{"query": "rust mcp"}"#.into(),
        };
        let args = tc.parsed_arguments().unwrap();
        assert_eq!(args["query"], "rust mcp");
    }

    #[test]
    fn tool_result_ok() {
        let r = ToolResult::ok("call_1", "found 5 results");
        assert!(r.success);
        assert_eq!(r.output, "found 5 results");
    }

    #[test]
    fn tool_result_err() {
        let r = ToolResult::err("call_1", "timeout");
        assert!(!r.success);
    }

    #[test]
    fn tool_definition_roundtrip() {
        let td = ToolDefinition {
            name: "test_tool".into(),
            description: "A test tool".into(),
            parameters: serde_json::json!({
                "type": "object",
                "properties": {
                    "input": { "type": "string" }
                }
            }),
            source: "builtin".into(),
        };
        let json = serde_json::to_string(&td).unwrap();
        let parsed: ToolDefinition = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.name, "test_tool");
    }
}
